### PR TITLE
Cap adjustments

### PR DESCRIPTION
**Pull request by werebus**
This fixes the "only @dfaulken can deploy" problem (also does some other Capistrano tweaking).

### CODE REVIEW

**Comment by dfaulken** [comment]
As much as I like being the only person with the key...

Build passes, merging.

**Comment by dfaulken** [comment]
@werebus, same thing over on jobapps? I can take care of that if you like.

**Comment by werebus** [comment]
I've got it

**Comment by dfaulken** [comment]
Great. This is deployed.

**Pull request merged**
